services:
  ui:
    build: ./ruby-stonks-ui
    ports:
      - "${UI_PORT:-3000}:${UI_PORT:-3000}"
    depends_on:
      - api
    environment:
      NEXTAUTH_URL: ${UI_BASE_URL:-"http://localhost:3000"}
      PORT: ${UI_PORT:-3000}
      GITHUB_CLIENT_ID: ${UI_GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${UI_GITHUB_CLIENT_SECRET}
      JWT_AUTH_SECRET: ${UI_AUTH_SECRET}
      STONKS_CLIENT_ID: ${UI_STONKS_CLIENT_ID}
      STONKS_CLIENT_SECRET: ${UI_STONKS_CLIENT_SECRET}
      STONKS_CLIENT_HOST: ${UI_STONKS_HOST:-http://api:3001}

  api:
    build: ./ruby-stonks-api
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"
    depends_on:
      - db
    environment:
      PORT: ${API_PORT:-3001}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ruby_stonks}
      POSTGRES_POOL: ${POSTGRES_POOL:-5000}
      POSTGRES_TIMEOUT: ${POSTGRES_TIMEOUT:-5}
      OAUTH_JWT_SECRET: ${API_AUTH_SECRET}
  db:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ruby_stonks
volumes:
  pg_data:
